# Generated by Django 3.2.5 on 2022-01-28 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='highest_bid_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hihgest', to=settings.AUTH_USER_MODEL),
        ),
    ]
